### ISSUE TITLE
Digest::SHA256#hexdigest and ObjectHash.hexdigest return different results

### ISSUE THREAD

**Issue by grempe** [cryptosphere/objecthash-ruby#2]
I'm trying to understand why the results of calling #digest on a Digest::SHA256.new and ObjectHash.digest are the same, but calling #hexdigest on ObjectHash provides a different result.

I setup a `Digest::SHA256` instance the same way that ObjectHash does internally.

Same Results

```
> h = Digest::SHA256.new
#<Digest::SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855>
> h.update "u"
#<Digest::SHA256: 0bfe935e70c321c7ca3afc75ce0d0ca2f98b5422e008bb31c00c6d7f1f1c0ad6>
> h.update "foo"
#<Digest::SHA256: a6a6e5e783c363cd95693ec189c2682315d956869397738679b56305f2095038>
> h.digest
"\xA6\xA6\xE5\xE7\x83\xC3c\xCD\x95i>\xC1\x89\xC2h#\x15\xD9V\x86\x93\x97s\x86y\xB5c\x05\xF2\tP8"

# matches h.digest exactly
> ObjectHash.digest "foo"
"\xA6\xA6\xE5\xE7\x83\xC3c\xCD\x95i>\xC1\x89\xC2h#\x15\xD9V\x86\x93\x97s\x86y\xB5c\x05\xF2\tP8"
```

Same : When using `.digest.unpack("h*").first` like ObjectHash does

```
# for #hexdigest these two can match, but you need to use .unpack("h*").first the same way
> h.digest.unpack("h*").first
"6a6a5e7e383c36dc5996e31c982c8632519d656839793768975b36502f900583"
> ObjectHash.hexdigest "foo"
"6a6a5e7e383c36dc5996e31c982c8632519d656839793768975b36502f900583"
```

Different : Digest::SHA256#hexdigest calculates hex differently 

```
irb(main):054:0> h.hexdigest
"a6a6e5e783c363cd95693ec189c2682315d956869397738679b56305f2095038"
```

Shouldn't `ObjectHash.hexdigest` return the hex the same way that
`Digest::SHA256#hexdigest` does? Especially considering the binary string #digest results
are returned the same.

**Comment by tarcieri** [comment]
Good catch! And a great reminder that I should add test vectors! 😄 

You're right! I should be using `H*` instead of `h*`, as the latter places the low nibble first.

**Comment by grempe** [comment]
Great, glad to help.

Any reason you left the fix on the fix-digest branch and didn't merge to master (or release)? :)

Thx

**Comment by tarcieri** [comment]
Well, the build failed:

https://travis-ci.org/cryptosphere/objecthash-ruby/builds/148745870

The test vectors are failing.

I honestly don't remember where I got them from. We should use test vectors from Ben Laurie's project:

https://github.com/benlaurie/objecthash/blob/master/objecthash_test.py

**Comment by grempe** [comment]
OK, so I fixed up the rubocop complaints (or disabled in some cases for that file) and now the tests are passing on Ruby 2.2, 2.3, Jruby.

Apparently though the string normalization method was not added until Ruby 2.2 so 2.0 and 2.1 are failing with:

```
 undefined method `unicode_normalize' for "ϓ":String
```

So, I'm not sure what to say about that since that method is required for parity with the python/go/c versions. Drop support for Ruby <2.2? Find another implementation of the normalization that works across modern rubies?

There is an apparently similar method in ActiveSupport 5.0, but I don't know if it depends on the same String#unicode_normalize under the hood.

http://api.rubyonrails.org/classes/ActiveSupport/Multibyte/Unicode.html#method-i-normalize

And of course there are still some disabled tests that need to be fixed related to number handling.

**Comment by tarcieri** [comment]
> Drop support for Ruby <2.2?

I'm fine with this

**Comment by grempe** [comment]
Dropped support for MRI < 2.2 in commit 36f808b264a65aa16538aa731d5d72eb3fd48061 in PR #4 

All specs currently green on Travis CI (but the specs still have commented out breakage in them)

**Comment by grempe** [comment]
Perhaps this issue should still stay open since there the handling of floats is still broken (possibly arrays too).  Or shall I open another issue for that?  I've been looking at the normalize floats method and comparing to output from `objecthash` Python but I have not discovered the issue yet.

**Comment by tarcieri** [comment]
Can you open a new issue specific to the current problems after this landed?

**Comment by grempe** [comment]
Sure.
